apiVersion: v1
kind: ServiceAccount
metadata:
  name: bistro-pipeline
  namespace: ds551-2026-spring-a5f0d1
  labels:
    app.kubernetes.io/name: bistro-pipeline
    app.kubernetes.io/part-of: petit-agile-bistro-order-pipeline
